### ISSUE TITLE
Can't log in. gConnect doesn't seem to do anything.

### ISSUE THREAD

**Issue by alberto139** [sagarchoudhary96/P5-Item-Catalog#1]
Hi sagarchoudhary96,

This is the best version of this project I've seen so far!
However it seems that the way Udacity intends for the google login doesn't work. Not just on your version but on all the ones I've seen, including the Udacity lesson example code.

I've tried it on your live version and local with my own client id.
I was wondering if it ever worked for you and if you have any ideas of how to fix it.

Cheers!

**Comment by sagarchoudhary96** [comment]
hey @alberto139 , it's working fine on the live version. i checked it. what issue you are exactly facing with it ?

**Comment by alberto139** [comment]
I think I found the issue.

What I was experiencing was that after pressing the login button and signing in with my google account the login window would close and nothing else would happen. I still couldn't add books, and the login button still said "login" and not "logout". However I was testing this on Google Chrome. I tried it with Firefox and it works fine!

Not sure why it doesn't work with Chrome, but Firefox will do for now.

**Comment by sagarchoudhary96** [comment]
hey @alberto139, well i don't know why you are getting the issue with login on chrome, but I tested and it's working perfectly fine on chrome too.  But since you are able to run this. I'm closing this issue. Also will add steps to add authentication in readme too soon.
